/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SpiderCraft9972 (https://sketchfab.com/oscar.lopez.riviello)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ufo-ef687f700ed64686834aaa912ac0e70f
title: U.F.O.
Extended by: https://github.com/ThomvanDijk
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useInteraction } from '@react-three/xr'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('assets/ufo/scene.gltf')
  const { actions } = useAnimations(animations, group)
  
  let move = true
  let angle = 0

  // Runs when component is initialised or if actions is updated
  useEffect(() => {
    // Actions: hover flight abduction_rings
    actions.hover.play()
  }, [actions]);

  // Subscribe to the render-loop, runs every frame
  useFrame(() => {
    if (move) {
      // Move ufo vertically around the given position on the x and y plane
      angle += props.speed
      group.current.position.y = props.position[1] + Math.sin(angle) * props.orbit_radius
      group.current.position.x = props.position[0] + Math.cos(angle) * props.orbit_radius
    }

    // Rotate ufo towards the origin of the rotation (center of earth)
    const rotation_z = Math.atan2(props.position[1] - group.current.position.y, props.position[0] - group.current.position.x)
    group.current.rotation.z = rotation_z + Math.PI / 2

  });

  useInteraction(group, 'onSelect', () => {
    move = !move

    if (move) {
      actions.abduction_rings.stop()
      actions.hover.play()
    } else {
      actions.hover.stop()
      actions.abduction_rings.play()
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[2, 2, 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[0.01, 0.01, 0.01]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_17.geometry}
              material={materials.material_0}
              skeleton={nodes.Object_17.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('assets/ufo/scene.gltf')
