/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jean Carlo (https://sketchfab.com/joycarllo7)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/foguete-animacao-e72c3d3d39ef4fb0a00e3664869420ed
title: Foguete Animação
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('assets/foguete/scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions); // hover flight abduction_rings
    actions.['Take 001'].play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="polySurface3" position={[-33, 7, 8]} rotation={[0, -0.93, 0]}>
            <mesh geometry={nodes.polySurface3_Corpo_0.geometry} material={materials.Corpo} />
            <mesh geometry={nodes.polySurface3_Base_0.geometry} material={materials.Base} />
            <mesh geometry={nodes.polySurface3_Bolinhas_0.geometry} material={materials.Bolinhas} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('assets/foguete/scene.gltf')
