/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SpiderCraft9972 (https://sketchfab.com/oscar.lopez.riviello)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ufo-ef687f700ed64686834aaa912ac0e70f
title: U.F.O.
*/

import React, { useRef, useEffect, useCallback } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('assets/ufo/scene.gltf')
  const { actions } = useAnimations(animations, group)
  
  let hover = true

  useEffect(() => {
    // Actions: hover flight abduction_rings
    actions.hover.play()
  });

  const handleClick = useCallback(e => {
    hover = !hover

    if (hover) {
      actions.abduction_rings.stop()
      actions.hover.play()
      group.current.position.y += 0.2 // Animation offset, blame the artist
    } else {
      actions.hover.stop()
      actions.abduction_rings.play()
      group.current.position.y -= 0.2
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[2, 2, 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[0.01, 0.01, 0.01]}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              onClick={handleClick}
              geometry={nodes.Object_17.geometry}
              material={materials.material_0}
              skeleton={nodes.Object_17.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('assets/ufo/scene.gltf')
