/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anthonely Lora (https://sketchfab.com/anthonely.lora)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/6147a6768e464e9b9b76c22ab05d4f26
title: Yeti - 01 Space Ship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('assets/yeti_ship/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-100.1, 0, 0]} rotation={[0, 0, 0]} />
          <group position={[0, -4.61, 0]}>
            <mesh geometry={nodes.polySurface26_blinn2_0.geometry} material={materials.blinn2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('assets/yeti_ship/scene.gltf')
